### ISSUE TITLE
Request error with Nuxt 3.7

### ISSUE THREAD

**Issue by henrikaskj** [uib-ub/uib-ub-monorepo#184]
Nuxt 3.7 does not play well with the monorepo. When I add a fresh nuxt app without any other packages I get the same error message as in this issue:
https://github.com/nuxt/nuxt/issues/22899

**Comment by henrikaskj** [comment]
C:\Users\has022\repos\monorepo>npm list nuxt
uib-ub-monorepo@1.0.0 C:\Users\has022\repos\monorepo
+-- nuxt-debug@ -> .\apps\nuxt-debug
| +-- @nuxt/devtools@0.8.4
| | +-- @nuxt/devtools-kit@0.8.4
| | | `-- nuxt@3.7.3 deduped
| | `-- nuxt@3.7.3 deduped
| `-- nuxt@3.7.3
+-- sps-ordbokene-web@ -> .\apps\sps-ordbokene-web
| `-- nuxt@3.7.3
`-- sps-termportal-web@1.0.0 -> .\apps\sps-termportal-web
  +-- @vueuse/nuxt@9.13.0
  | `-- nuxt@3.2.3
  `-- nuxt@3.5.1

**Comment by henrikaskj** [comment]
npm list nuxt outputs the following tree:
![image](https://github.com/uib-ub/uib-ub-monorepo/assets/22298175/186902ca-16ea-4863-a643-74367182530d)

**Comment by tarjelavik** [comment]
Will be gone when orbokene leaves the monorepo, but could happen to termportalen? @jobangen?

**Comment by jobangen** [comment]
I'm not sure what exactly caused this issue and I don't think trying to reproduce it adds much value.
If there was a nuxt bug, it was probably fixed in 3.7.4. and won't impact us in the future.
